SET NAMES UTF8;
DROP DATABASE IF EXISTS sz;
CREATE DATABASE sz CHARSET=UTF8;
USE sz;

CREATE TABLE sz_user(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(32) UNIQUE,
	upwd VARCHAR(32),
	phone VARCHAR(16) NOT NULL UNIQUE,
	lei VARCHAR(16)
);
INSERT INTO sz_user VALUES('1','123','123456','123456789','student');

